export const sentimentEvaluationSet = [
  { text: 'I am happy with how this turned out.', label: 'positive' },
  { text: 'The team delivered an excellent result.', label: 'positive' },
  { text: 'That was a thoughtful and generous gesture.', label: 'positive' },
  { text: 'I really enjoyed the workshop today.', label: 'positive' },
  { text: 'Your explanation was clear and helpful.', label: 'positive' },
  { text: 'The new design feels fresh and welcoming.', label: 'positive' },
  { text: 'I am grateful for your quick response.', label: 'positive' },
  { text: 'This is exactly what I needed.', label: 'positive' },
  { text: 'The staff handled the situation wonderfully.', label: 'positive' },
  { text: 'I would gladly recommend this service.', label: 'positive' },
  { text: 'The performance was impressive from start to finish.', label: 'positive' },
  { text: 'We made strong progress this week.', label: 'positive' },
  { text: 'I feel confident about the plan.', label: 'positive' },
  { text: 'The meal was delicious and beautifully prepared.', label: 'positive' },
  { text: 'Thank you, that solved my problem.', label: 'positive' },
  { text: 'The update made the application much easier to use.', label: 'positive' },
  { text: 'I am pleasantly surprised by the quality.', label: 'positive' },
  { text: 'The results were better than I expected.', label: 'positive' },
  { text: 'It was a lovely morning with good company.', label: 'positive' },
  { text: 'I absolutely love this approach.', label: 'positive' },
  { text: 'The support agent was patient and kind.', label: 'positive' },
  { text: 'This product has exceeded my expectations.', label: 'positive' },
  { text: 'The event was lively, organized, and enjoyable.', label: 'positive' },
  { text: 'I am proud of the work we completed.', label: 'positive' },
  { text: 'That solution is clever and practical.', label: 'positive' },
  { text: 'Good morning, I hope your day is going well.', label: 'positive' },
  { text: 'The friendly welcome made me feel comfortable.', label: 'positive' },
  { text: 'I do not regret choosing this option.', label: 'positive' },
  { text: 'I am not unhappy with the final result.', label: 'positive' },
  { text: "I don't hate the new layout.", label: 'positive' },
  { text: 'This is surprisingly good for a first attempt.', label: 'positive' },
  { text: 'I expected this to be terrible, but it was excellent.', label: 'positive' },
  { text: 'The presentation was boring at first but became fascinating.', label: 'positive' },
  { text: 'The product is good, and the customer service was even better.', label: 'positive' },
  { text: 'That was fucking amazing.', label: 'positive' },
  { text: 'I absolutely love this, you idiots.', label: 'positive' },
  { text: 'Hello Good Morning.', label: 'positive' },
  { text: 'The delay was frustrating, but the final work was excellent.', label: 'positive' },
  { text: 'I was nervous, yet everyone treated me with respect.', label: 'positive' },
  { text: 'The repair took time, but it works perfectly now.', label: 'positive' },
  { text: 'I thought the meeting would be difficult, but it was productive.', label: 'positive' },
  { text: 'The instructions were long, though they were genuinely useful.', label: 'positive' },
  { text: 'I am excited to see what happens next.', label: 'positive' },
  { text: 'The small improvement made a big difference.', label: 'positive' },
  { text: 'You did a great job despite the delay.', label: 'positive' },
  { text: 'The result is acceptable and better than last time.', label: 'positive' },
  { text: 'I appreciate the honest and constructive feedback.', label: 'positive' },
  { text: 'I am relieved that everything worked out.', label: 'positive' },
  { text: 'The celebration was warm, peaceful, and memorable.', label: 'positive' },
  { text: 'This is a meaningful improvement for everyone involved.', label: 'positive' },

  { text: 'The meeting starts at 10 AM tomorrow.', label: 'neutral' },
  { text: 'My name is Dhanashri.', label: 'neutral' },
  { text: 'The weather is 25 degrees today.', label: 'neutral' },
  { text: 'I have a meeting tomorrow afternoon.', label: 'neutral' },
  { text: 'The package arrived at the front desk.', label: 'neutral' },
  { text: 'Please send the revised document by Friday.', label: 'neutral' },
  { text: 'The train leaves from platform three.', label: 'neutral' },
  { text: 'The account was created last month.', label: 'neutral' },
  { text: 'There are four chairs in the room.', label: 'neutral' },
  { text: 'The appointment is scheduled for Tuesday.', label: 'neutral' },
  { text: 'Could you tell me where the library is?', label: 'neutral' },
  { text: 'What time does the store close?', label: 'neutral' },
  { text: 'The report contains twelve pages.', label: 'neutral' },
  { text: 'I am checking the latest delivery status.', label: 'neutral' },
  { text: 'The blue folder is on my desk.', label: 'neutral' },
  { text: 'She moved to Chicago in 2022.', label: 'neutral' },
  { text: 'The server restarted at midnight.', label: 'neutral' },
  { text: 'Our class begins after lunch.', label: 'neutral' },
  { text: 'The invoice number is 4831.', label: 'neutral' },
  { text: 'I will call you after the appointment.', label: 'neutral' },
  { text: 'The museum is closed on Mondays.', label: 'neutral' },
  { text: 'This document needs a signature on the last page.', label: 'neutral' },
  { text: 'The package weighs two kilograms.', label: 'neutral' },
  { text: 'We are reviewing the schedule this morning.', label: 'neutral' },
  { text: 'The office has moved to the second floor.', label: 'neutral' },
  { text: 'Hello, can you hear me?', label: 'neutral' },
  { text: 'Good morning, the meeting is at nine.', label: 'neutral' },
  { text: 'I received your message yesterday.', label: 'neutral' },
  { text: 'The device uses a USB-C cable.', label: 'neutral' },
  { text: 'Please place the form in the blue tray.', label: 'neutral' },
  { text: 'The weather forecast says rain this evening.', label: 'neutral' },
  { text: 'I am not sure which room was reserved.', label: 'neutral' },
  { text: 'The customer asked about the return policy.', label: 'neutral' },
  { text: 'The presentation begins with a brief introduction.', label: 'neutral' },
  { text: 'Would you like tea or coffee?', label: 'neutral' },
  { text: 'The file was saved under the project folder.', label: 'neutral' },
  { text: 'My train ticket is in my email.', label: 'neutral' },
  { text: 'The clinic opens at eight o’clock.', label: 'neutral' },
  { text: 'He is waiting outside the conference room.', label: 'neutral' },
  { text: 'The survey closes at the end of the month.', label: 'neutral' },
  { text: 'I do not have any additional information.', label: 'neutral' },
  { text: 'The box contains a charger and a manual.', label: 'neutral' },
  { text: 'What is the reference number for this request?', label: 'neutral' },
  { text: 'The bus was scheduled to arrive at six.', label: 'neutral' },
  { text: 'Our team is meeting in the north office.', label: 'neutral' },
  { text: 'The form asks for a phone number.', label: 'neutral' },
  { text: 'I will review the notes before tomorrow.', label: 'neutral' },
  { text: 'The lights turn off automatically at ten.', label: 'neutral' },
  { text: 'This statement describes the current process.', label: 'neutral' },
  { text: 'The folder was moved without changing its contents.', label: 'neutral' },

  { text: 'I am extremely disappointed by the result.', label: 'negative' },
  { text: 'The service was slow and unhelpful.', label: 'negative' },
  { text: 'This experience was terrible.', label: 'negative' },
  { text: 'The product stopped working after one day.', label: 'negative' },
  { text: 'I regret making this purchase.', label: 'negative' },
  { text: 'The explanation was confusing and incomplete.', label: 'negative' },
  { text: 'The delay caused a serious problem for us.', label: 'negative' },
  { text: 'I am angry about how this was handled.', label: 'negative' },
  { text: 'The meal was cold and tasteless.', label: 'negative' },
  { text: 'The support team ignored my request.', label: 'negative' },
  { text: 'This decision will make things worse.', label: 'negative' },
  { text: 'I cannot recommend this service.', label: 'negative' },
  { text: 'The room was dirty when we arrived.', label: 'negative' },
  { text: 'The update created several new errors.', label: 'negative' },
  { text: 'I am worried about the missing information.', label: 'negative' },
  { text: 'The instructions were careless and misleading.', label: 'negative' },
  { text: 'That was a frustrating waste of time.', label: 'negative' },
  { text: 'The customer was rude and dismissive.', label: 'negative' },
  { text: 'The presentation failed to answer basic questions.', label: 'negative' },
  { text: 'I expected better from this company.', label: 'negative' },
  { text: 'The delivery was late and damaged.', label: 'negative' },
  { text: 'The plan is unrealistic and poorly organized.', label: 'negative' },
  { text: 'I absolutely hate this outcome.', label: 'negative' },
  { text: 'You are an idiot.', label: 'negative' },
  { text: 'You Son Of A Bitch.', label: 'negative' },
  { text: 'Hello Motherfucker.', label: 'negative' },
  { text: 'This is not good.', label: 'negative' },
  { text: 'I am not happy with this.', label: 'negative' },
  { text: 'I do not want to use this again.', label: 'negative' },
  { text: 'The result was worse than expected.', label: 'negative' },
  { text: 'The product is good, but the customer service was terrible.', label: 'negative' },
  { text: 'The report looked polished, but it contained serious errors.', label: 'negative' },
  { text: 'I hoped for a solution, but the issue remains unresolved.', label: 'negative' },
  { text: 'The food was good, but the service was disappointing.', label: 'negative' },
  { text: 'I did not love the experience.', label: 'negative' },
  { text: 'I do not think this is acceptable.', label: 'negative' },
  { text: 'The cheerful announcement could not hide the bad news.', label: 'negative' },
  { text: 'I thought the process would be easy, but it was exhausting.', label: 'negative' },
  { text: 'The result is not as good as promised.', label: 'negative' },
  { text: 'I expected better and received less.', label: 'negative' },
  { text: 'The meeting was supposed to help, but it created more confusion.', label: 'negative' },
  { text: 'The staff apologized, yet the problem was never fixed.', label: 'negative' },
  { text: 'That was fucking awful.', label: 'negative' },
  { text: 'The application crashes whenever I try to save.', label: 'negative' },
  { text: 'I am tired of repeating the same request.', label: 'negative' },
  { text: 'The instructions contradict each other.', label: 'negative' },
  { text: 'The outcome was frustrating despite the effort.', label: 'negative' },
  { text: 'This approach is unreliable and difficult to maintain.', label: 'negative' },
  { text: 'I am not satisfied with the response.', label: 'negative' },
  { text: 'The promised improvement never arrived.', label: 'negative' }
];

export const sentimentDevelopmentSet = [
  { text: 'The staff were welcoming and professional.', label: 'positive' },
  { text: 'I am pleased with the quick solution.', label: 'positive' },
  { text: 'The result was not disappointing.', label: 'positive' },
  { text: 'That was a genuinely kind thing to do.', label: 'positive' },
  { text: 'The service is better than I expected.', label: 'positive' },
  { text: 'The file is stored in the archive folder.', label: 'neutral' },
  { text: 'The appointment begins at three o’clock.', label: 'neutral' },
  { text: 'Can you confirm the room number?', label: 'neutral' },
  { text: 'The report was uploaded this morning.', label: 'neutral' },
  { text: 'I have not received the tracking number.', label: 'neutral' },
  { text: 'The result was disappointing and incomplete.', label: 'negative' },
  { text: 'I am not satisfied with the service.', label: 'negative' },
  { text: 'The change caused unexpected failures.', label: 'negative' },
  { text: 'I expected more from this product.', label: 'negative' },
  { text: 'The cheerful message announced a cancellation.', label: 'negative' },
  { text: 'I love the clarity of these instructions.', label: 'positive' },
  { text: 'Everything worked exactly as planned.', label: 'positive' },
  { text: 'The package is on the reception desk.', label: 'neutral' },
  { text: 'The office closes at five.', label: 'neutral' },
  { text: 'This is a frustrating and expensive mistake.', label: 'negative' },
  { text: "I don't dislike the new process.", label: 'positive' },
  { text: 'The weather is cloudy but stable.', label: 'neutral' },
  { text: 'The delivery was late, damaged, and unusable.', label: 'negative' },
  { text: 'That was surprisingly enjoyable.', label: 'positive' },
  { text: 'The question is listed on page four.', label: 'neutral' },
  { text: 'I cannot approve this version.', label: 'negative' },
  { text: 'The presentation was long but informative.', label: 'positive' },
  { text: 'The account has two authorized users.', label: 'neutral' },
  { text: 'This outcome is worse than the previous one.', label: 'negative' },
  { text: 'I am grateful for the thoughtful follow-up.', label: 'positive' },
  { text: 'I am happy.', label: 'positive' },
  { text: 'I am not happy.', label: 'negative' },
  { text: 'I am unhappy.', label: 'negative' },
  { text: 'I am not unhappy.', label: 'positive' },
  { text: 'I love this.', label: 'positive' },
  { text: "I don't love this.", label: 'negative' },
  { text: "I don't hate this.", label: 'positive' },
  { text: 'This is good.', label: 'positive' },
  { text: 'This is not good.', label: 'negative' },
  { text: 'This is surprisingly good.', label: 'positive' },
  { text: 'I expected better.', label: 'negative' },
  { text: 'I expected this to be terrible, but it was excellent.', label: 'positive' },
  { text: 'The product is good, but the customer service was terrible.', label: 'negative' },
  { text: 'Hello Good Morning.', label: 'positive' },
  { text: 'Hello Motherfucker.', label: 'negative' },
  { text: 'You Son Of A Bitch.', label: 'negative' },
  { text: 'The meeting starts at 10 AM.', label: 'neutral' },
  { text: 'My name is Dhanashri.', label: 'neutral' }
];
